ALTER TABLE plan ADD CONSTRAINT PK_PLAN PRIMARY KEY (
	plan_id
);

ALTER TABLE workOrder ADD CONSTRAINT PK_WORKORDER PRIMARY KEY (
	order_id
);

ALTER TABLE performance ADD CONSTRAINT PK_PERFORMANCE PRIMARY KEY (
	per_id
);

ALTER TABLE inspection ADD CONSTRAINT PK_INSPECTION PRIMARY KEY (
	ins_id
);

ALTER TABLE defect ADD CONSTRAINT PK_DEFECT PRIMARY KEY (
	defect_id
);

ALTER TABLE equipment ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (
	equip_id
);

ALTER TABLE maintenance ADD CONSTRAINT PK_MAINTENANCE PRIMARY KEY (
	main_id
);

ALTER TABLE bom ADD CONSTRAINT PK_BOM PRIMARY KEY (
	bom_id
);

ALTER TABLE product ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	product_id
);

ALTER TABLE inventory ADD CONSTRAINT PK_INVENTORY PRIMARY KEY (
	inventory_id
);

ALTER TABLE stockmove ADD CONSTRAINT PK_STOCKMOVE PRIMARY KEY (
	move_id
);

ALTER TABLE returninventory ADD CONSTRAINT PK_RETURNINVENTORY PRIMARY KEY (
	return_id
);

ALTER TABLE material ADD CONSTRAINT PK_MATERIAL PRIMARY KEY (
	material_id
);

ALTER TABLE materialRequest ADD CONSTRAINT PK_MATERIALREQUEST PRIMARY KEY (
	request_id
);

ALTER TABLE emp ADD CONSTRAINT PK_EMP PRIMARY KEY (
	user_id
);

ALTER TABLE dept ADD CONSTRAINT PK_DEPT PRIMARY KEY (
	dept_id
);

ALTER TABLE board ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	board_id
);

ALTER TABLE posts ADD CONSTRAINT PK_POSTS PRIMARY KEY (
	post_id
);

ALTER TABLE comments ADD CONSTRAINT PK_COMMENTS PRIMARY KEY (
	comment_id
);

ALTER TABLE client ADD CONSTRAINT PK_CLIENT PRIMARY KEY (
	client_id
);

ALTER TABLE sales_order ADD CONSTRAINT PK_SALES_ORDER PRIMARY KEY (
	order_id
);

ALTER TABLE sales_order_details ADD CONSTRAINT PK_SALES_ORDER_DETAILS PRIMARY KEY (
	detail_id
);

ALTER TABLE cost ADD CONSTRAINT PK_COST PRIMARY KEY (
	cost_id
);

ALTER TABLE Equip_downtime ADD CONSTRAINT PK_EQUIP_DOWNTIME PRIMARY KEY (
	downtime_id
);

ALTER TABLE monitoring ADD CONSTRAINT PK_MONITORING PRIMARY KEY (
	monitoring_id
);

ALTER TABLE quality_standard ADD CONSTRAINT PK_QUALITY_STANDARD PRIMARY KEY (
	standard_id
);

ALTER TABLE material_move ADD CONSTRAINT PK_MATERIAL_MOVE PRIMARY KEY (
	move_id
);